### ISSUE TITLE
TypeErrors

### ISSUE THREAD

**Issue by sevstafiev** [Ibotta/mr_uplift#39]
Tried to reproduce results of Quick Start Example but got a TypeError: predict_optimal_treatments() got an unexpected keyword argument 'weights'. After taking off weights parameter in uplift_model.predict_optimal_treatments got TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'. Using Python 3.6.8.

**Comment by samcarlos** [comment]
@sevstafiev Hey thanks for reporting the issue. Can you please let me know which example your referring to and which cell you're trying to run? Thanks!

**Comment by sevstafiev** [comment]
Hey, I just copypasted Example from readme and tried to run it.
Fitting went smoothly but uplift_model.predict_optimal_treatments caused problems.

**Comment by samcarlos** [comment]
Ah I thought you were referring to the [notebook examples](https://github.com/Ibotta/mr_uplift/tree/master/examples). 

If you run `uplift_model.predict_optimal_treatments(x_new, objective_weights = np.array([.6,-.4,0,0]).reshape(1,-1))` instead it will run. 

I will change the quickstart example shortly. Let me know if you have any other questions or find any other issues. 

Thanks,
Sam

**Comment by sevstafiev** [comment]
Thanks! Keep in touch.

**Comment by sevstafiev** [comment]
May I ask you please, is it available to get heterogeneous treatment with multitreatment (like .effect in EconML)? As I understood, get_erupt_curves() gives mean uplifts for each type of treatment only for test dataset. My goal is to plot uplift curves due to deciles.

**Comment by samcarlos** [comment]
Hey @sevstafiev,

You can get the expected values of each response variable and treatment combination for all users with the `.predict_ice` function. See [`here`](https://github.com/Ibotta/mr_uplift/blob/master/mr_uplift/mr_uplift.py#L243). 

Not sure if that's what you're going for. Happy to help if you can describe what you're looking for in more detail or can provide references. 

Thanks,
Sam

**Comment by sevstafiev** [comment]
As I understood, if observations without treatment have category treatment='0', and, for example, one of other treatments has category treatment='3' we can get uplift for each user for treatment=3 like this: uplift_model.predict_ice(test,treatments='3')-uplift_model.predict_ice(test,treatments='0')?

**Comment by samcarlos** [comment]
In this framework you'll have to dummy out those category treatments. So you might have 

`treatments = [ [1, 0, 0]
                         [0, 1, 0]
                         [0, 0, 1] ]`

Running `uplift_model.predict_ice(test,treatments=treatments)` will output expected response for each treatment. 

To get the expected lift you can find the appropriate columns of the output corresponding to your treatments of interest and subtract those.
