### ISSUE TITLE
Example for multiple treatment needed!

### ISSUE THREAD

**Issue by tinytuna84hh** [Ibotta/mr_uplift#51]
Hello, the repo states that multiple treatments (along with multiple outcomes) are enabled. 

In my case I have 3 treatments which are continuous such as Price, discount, and quality. I want to see how different combinations of treatments impact demand. 

Can someone please post an example in python?

**Comment by samcarlos** [comment]
Hey @tinytuna84hh,

Please take a look [here](http://scweiss.blogspot.com/2020/06/the-mruplift-package-in-r-practitioners.html) or in the examples [here](https://github.com/Ibotta/mr_uplift/blob/master/examples/mr_uplift_one_response_example.ipynb). The treatment input t can be multivariate.

If you post some example data I can walk you through it. 

Thanks,
Sam

**Comment by tinytuna84hh** [comment]
Hi Sam, thank you for the message. I will take a look. 

On another note, do you have the capability to integrate something into the model which provides a monotone decrease in the outcome variable as treatment values increase?

for example, increasing the price of a product may move revenue up to a threshold (if any) but then revenue will drop as no one will pay infinite amounts anymore. Let me know how I could get this baked Into your model suite.

**Comment by samcarlos** [comment]
Hey @tinytuna84hh,

I think something like revenue would need a non-monodic relationship. Something like demand could require that. But the mr_uplift package does not support that right now (not really sure how to do that for heterogeneous treatment effects). In practice the model is pretty good at retaining monotonic effects out of the box.

I suggest trying it out and posting some examples so I can understand what you're trying to do more clearly. If there are some discrepancies I'd be happy to discuss ways to improve. 

Thanks,
Sam

**Comment by samcarlos** [comment]
Hey @tinytuna84hh,

Can I close this? 

Thanks,
Sam
