### ISSUE TITLE
SIGKILL(-9) memory problem from gridsearch 

### ISSUE THREAD

**Issue by CoteDave** [Ibotta/mr_uplift#56]
Hi, 
I have a SIGKILL(-9) memory problem on a ~3millions rows, ~150 columns dataset with a 12CPU 128g memory resources, with unique discrete treatment (T) and discrete target (y).

I also tried with a basic NN architecture:
![image](https://user-images.githubusercontent.com/49559881/203992055-3a5b783a-4f6b-45a5-aaf5-736721028ad4.png)

![image](https://user-images.githubusercontent.com/49559881/203991142-d601800d-d290-4660-a954-6d2ccb04f755.png)

I found this strange as I can easily train this same dataset using a keras classifier model or a torch model. Also have tried a torch tarnet (from catenets) and everthing works fine. I was wondering why MrUplift have this memory problem on this dataset as it should use keras NN under the hood ? Can we disable the grid search option (as it seems to come from here) ? can it be optimized ?

Thanks !

**Comment by CoteDave** [comment]
Hi again, 

I just "hacked" the gridsearch to bypass it and it worked ! No more memory problems... 

Maybe you could add the option to not use the gridearch ?

![image](https://user-images.githubusercontent.com/49559881/203996053-9221eaf4-4e2e-4ede-a036-3b732e9dfb5d.png)

![image](https://user-images.githubusercontent.com/49559881/203996134-59e211d2-b4d5-493e-9c16-9f638915a940.png)

![image](https://user-images.githubusercontent.com/49559881/203995954-a1ea6178-d0ca-4397-a79a-74d65344aa3b.png)

**Comment by samcarlos** [comment]
Can you do me a favor and try running it with `n_jobs=1`? 

Yea perhaps there could be a pass through but I don’t think I want to condone building a net without doing some hyper parameter tuning first :)

**Comment by CoteDave** [comment]
Hi,

I passed a lot of time trying multiple combinations to get this work ...  Tried with 1, 2, 3, 6 cores... Changed all parameters... Same thing, sigkill9 - memory error.... But when I get rid of the sklearn gridsearch code part everything works  faster even if I have only one choice by param in the param dict

**Comment by samcarlos** [comment]
Ok. Does it work if you run it with a few thousand observations? 

Yes it makes sense if you get rid of gridsearch it runs faster

**Comment by CoteDave** [comment]
Yes, if I reduce the sample to 10% of the original data of 3 millions rows it works with gridsearch.

**Comment by samcarlos** [comment]
Ok. Bypassing grid search is probably a good thing to have. I'll tag this as an enhancement as I don't think memory issues are necessarily bugs in the code itself. 

Also one of the assumptions of using that model is that the treatments are randomly assigned. Having 3 million observations of randomized data is pretty large. Are they randomly assigned? If not I suggest looking at the propensity score methodology https://github.com/Ibotta/mr_uplift/blob/master/examples/mr_uplift_propensity_score.ipynb

Even if they are randomly assigned I've gotten better results using the propensity scores fwiw

**Comment by CoteDave** [comment]
Thanks a lot!

For the randomly assigned / unconfoundness assumption, not sure if it's the best thing to do but I first check with a Model X to predict T to see if there is any treatment bias. If there is some, I remove the features that contribute to give a predictive power X-->T. When my treatment model performance is "random", then I use Uplift Model with removed features X-T --> Y. 

Will definitly try the propensity scores to see if I can obtain better performance!

**Comment by samcarlos** [comment]
You break my heart Dave!

You should control for features where x — >T not remove them :) 

I think you’d have better results if you include all variables and use the propensity option
